### ISSUE TITLE
Errors when running setup.py build

### ISSUE THREAD

**Issue by wayfarerboy** [vmg/SkeletonJelly#1]
Hi.  I'm very excited about the possibility of using OpenNI from python as, try as I might, I just can't get my head around C++.  However, upon running setup.py build, I get some errors that stop the build process.  I'm using Ubuntu 10.10 with a working installation of OpenNI (1.0.0.25) and NITE (1.3.0.18) libraries:

<code>$ export OPEN_NI_LIB=/usr/lib
<code>$ export OPEN_NI_INCLUDE=/usr/include/ni
<code>$ python setup.py build
running build
running build_py
file swig/skeletonjelly.py (for module skeletonjelly) not found
file swig/skeletonjelly.py (for module skeletonjelly) not found
running build_ext
building '_skeletonjelly' extension
swigging swig/skeletonjelly.i to swig/skeletonjelly_wrap.cpp
swig -python -c++ -o swig/skeletonjelly_wrap.cpp swig/skeletonjelly.i
creating build
creating build/temp.linux-i686-2.6
creating build/temp.linux-i686-2.6/src
creating build/temp.linux-i686-2.6/swig
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/ni -I/usr/include/python2.6 -c src/skeletonjelly.cpp -o build/temp.linux-i686-2.6/src/skeletonjelly.o /Zi /EHsc
gcc: /Zi: No such file or directory
gcc: /EHsc: No such file or directory
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
In file included from src/skeletonjelly.hpp:6,
                 from src/skeletonjelly.cpp:1:
<code>/usr/include/ni/XnCppWrapper.h: In constructor ‘xn::OutputMetaData::OutputMetaData(const XnUInt8*_)’:
/usr/include/ni/XnCppWrapper.h:214: warning: ‘xn::OutputMetaData::m_nAllocatedSize’ will be initialized after
/usr/include/ni/XnCppWrapper.h:208: warning:   ‘XnUInt8_ xn::OutputMetaData::m_pAllocatedData’
/usr/include/ni/XnCppWrapper.h:93: warning:   when initialized here
/usr/include/ni/XnCppWrapper.h: In constructor ‘xn::EnumerationErrors::EnumerationErrors()’:
/usr/include/ni/XnCppWrapper.h:4103: warning: ‘xn::EnumerationErrors::m_bAllocated’ will be initialized after
/usr/include/ni/XnCppWrapper.h:4102: warning:   ‘XnEnumerationErrors\* xn::EnumerationErrors::m_pErrors’
/usr/include/ni/XnCppWrapper.h:4003: warning:   when initialized here
/usr/include/ni/XnCppWrapper.h: In constructor ‘xn::EnumerationErrors::EnumerationErrors(XnEnumerationErrors_, XnBool)’:
/usr/include/ni/XnCppWrapper.h:4103: warning: ‘xn::EnumerationErrors::m_bAllocated’ will be initialized after
/usr/include/ni/XnCppWrapper.h:4102: warning:   ‘XnEnumerationErrors_ xn::EnumerationErrors::m_pErrors’
/usr/include/ni/XnCppWrapper.h:4011: warning:   when initialized here
/usr/include/ni/XnCppWrapper.h: In member function ‘XnStatus xn::NodeInfo::GetInstance(xn::ProductionNode&) const’:
/usr/include/ni/XnCppWrapper.h:4612: warning: unused variable ‘nRetVal’
In file included from src/skeletonjelly.cpp:1:
src/skeletonjelly.hpp: At global scope:
src/skeletonjelly.hpp:153: error: ‘INFINITE’ was not declared in this scope
src/skeletonjelly.hpp: In member function ‘bool Kinect::userActive(XnUserID)’:
src/skeletonjelly.hpp:170: warning: comparison between signed and unsigned integer expressions
src/skeletonjelly.cpp: In member function ‘void Kinect::tick()’:
src/skeletonjelly.cpp:154: error: ‘GetTickCount’ was not declared in this scope
src/skeletonjelly.cpp:165: error: ‘Sleep’ was not declared in this scope
src/skeletonjelly.cpp: In member function ‘void Kinect::onNewUser(XnUserID)’:
src/skeletonjelly.cpp:206: warning: comparison between signed and unsigned integer expressions
error: command 'gcc' failed with exit status 1</code>

**Comment by vmg** [comment]
Hey, sorry about that. I had never tried compiling on Linux before. I think right now it will compile cleanly (except for the warnings in OpenNI's CPP headers) in both the Experimental and Stable version of OpenNI.

Tell me if you find any issues, happy hacking.

**Comment by wayfarerboy** [comment]
Brilliant.  Just a few warnings, as you mentioned, but has built and installed successfully using unstable OpenNI.  Thanks a lot.
