### ISSUE TITLE
No (very little) output from Python library

### ISSUE THREAD

**Issue by fsto** [vmg/SkeletonJelly#5]
First, your Python example (*link below) works fine with the CoM.
When trying to add more or less any of the other functions, eg. getJoint I don't get any output. And the rest of the function kinect_callback never seems to be run, but no exceptions are raised. The following line was added after your print k.getCoM(True)
        print k.getJoint(9, True, user_id)  # XN_SKEL_LEFT_HAND

*link: https://github.com/tanoku/SkeletonJelly/blob/0fcdb7072ce3d5747d97b43af1ae57798f87df67/examples/example.py

My kinect_callback function in example.py:
    def kinect_callback(cb_type, user_id):
        messages = [
            "New user",
            "Lost user",
            "Pose detected",
            "Calibration start",
            "Calibration success!",
            "Calibration failed"
        ]
        print "CB [User %d]: %s" % (user_id, messages[cb_type])
        if cb_type == 4:
            calibrated = True
            print k.getCoM(True)
            print k.getJoint(9, True, user_id)  # XN_SKEL_LEFT_HAND
            print "I'm (and the print right above) never printed"

**Comment by vmg** [comment]
Hey fsto. Unfortunately, the SkeletonJelly library is being written for a research project, and we've decided to drop Python and stick to C++ for all the project. That means I won't be supporting the Python bindings as the library progresses. Sorry about the inconvenience!

You are of course welcome to clone the library and update the bindings yourself. :)
